name: twitter_api_core
description: This package provides core reusable and useful functionality for wrapping Twitter API with Dart.
version: 1.5.1
repository: https://github.com/twitter-dart/twitter-api-core
issue_tracker: https://github.com/twitter-dart/twitter-api-core/issues
homepage: https://github.com/twitter-dart/twitter-api-v2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^0.13.5
  mime: ^1.0.2
  oauth1: ^2.0.0
  freezed_annotation: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  import_sorter: ^4.6.0
